# Generated by Django 4.2.2 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
