# Generated by Django 4.2.2 on 2023-07-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_text',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default='', max_length=6000000),
        ),
    ]
