# Generated by Django 4.2.3 on 2023-08-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
